// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cryptonft/cryptonft.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ClassMetadata struct {
	// creator defines creator of NFT classification
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// mintRestricted specifies whether NFT classification restricts minting NFTs by others
	MintRestricted bool `protobuf:"varint,2,opt,name=mintRestricted,proto3" json:"mintRestricted,omitempty"`
	// burnRestricted specifies whether NFT classification restricts burning NFTs by others
	BurnRestricted bool `protobuf:"varint,3,opt,name=burnRestricted,proto3" json:"burnRestricted,omitempty"`
	// updateRestricted specifies whether NFT classification restricts updating NFTs by others
	UpdateRestricted bool `protobuf:"varint,4,opt,name=updateRestricted,proto3" json:"updateRestricted,omitempty"`
	// data is the app specific metadata of the NFT class. Optional
	Data *types.Any `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ClassMetadata) Reset()         { *m = ClassMetadata{} }
func (m *ClassMetadata) String() string { return proto.CompactTextString(m) }
func (*ClassMetadata) ProtoMessage()    {}
func (*ClassMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3526443614ef418, []int{0}
}
func (m *ClassMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClassMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClassMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClassMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassMetadata.Merge(m, src)
}
func (m *ClassMetadata) XXX_Size() int {
	return m.Size()
}
func (m *ClassMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ClassMetadata proto.InternalMessageInfo

func (m *ClassMetadata) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ClassMetadata) GetMintRestricted() bool {
	if m != nil {
		return m.MintRestricted
	}
	return false
}

func (m *ClassMetadata) GetBurnRestricted() bool {
	if m != nil {
		return m.BurnRestricted
	}
	return false
}

func (m *ClassMetadata) GetUpdateRestricted() bool {
	if m != nil {
		return m.UpdateRestricted
	}
	return false
}

func (m *ClassMetadata) GetData() *types.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ClassMetadata)(nil), "devashishdxt.cryptonft.cryptonft.ClassMetadata")
}

func init() { proto.RegisterFile("cryptonft/cryptonft.proto", fileDescriptor_b3526443614ef418) }

var fileDescriptor_b3526443614ef418 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x63, 0x28, 0x7f, 0x46, 0x20, 0x64, 0x31, 0xa4, 0x0c, 0x56, 0xc4, 0x80, 0x22, 0x24,
	0x6c, 0x09, 0x78, 0x01, 0x60, 0x86, 0x21, 0x23, 0x9b, 0x13, 0xbb, 0x49, 0xa4, 0xd6, 0x8e, 0xec,
	0x1b, 0xd4, 0xbc, 0x05, 0x8f, 0xc5, 0x46, 0x47, 0x46, 0x94, 0xbc, 0x08, 0x4a, 0x42, 0x9b, 0x40,
	0xb7, 0xeb, 0xe3, 0xcf, 0xf2, 0x3d, 0x1f, 0x9e, 0x26, 0xb6, 0x2a, 0xc0, 0xe8, 0x19, 0xf0, 0xcd,
	0xc4, 0x0a, 0x6b, 0xc0, 0x90, 0x40, 0xaa, 0x37, 0xe1, 0xb2, 0xdc, 0x65, 0x72, 0x09, 0x6c, 0xb8,
	0xdd, 0x4c, 0x17, 0xd3, 0xd4, 0x98, 0x74, 0xae, 0x78, 0xc7, 0xc7, 0xe5, 0x8c, 0x0b, 0x5d, 0xf5,
	0x8f, 0x2f, 0x3f, 0x11, 0x3e, 0x79, 0x9a, 0x0b, 0xe7, 0x9e, 0x15, 0x08, 0x29, 0x40, 0x10, 0x1f,
	0x1f, 0x24, 0x56, 0x09, 0x30, 0xd6, 0x47, 0x01, 0x0a, 0x8f, 0xa2, 0xf5, 0x91, 0x5c, 0xe1, 0xd3,
	0x45, 0xae, 0x21, 0x52, 0x0e, 0x6c, 0x9e, 0x80, 0x92, 0xfe, 0x4e, 0x80, 0xc2, 0xc3, 0xe8, 0x5f,
	0xda, 0x72, 0x71, 0x69, 0xf5, 0x88, 0xdb, 0xed, 0xb9, 0xbf, 0x29, 0xb9, 0xc6, 0x67, 0x65, 0x21,
	0x05, 0xa8, 0x11, 0x39, 0xe9, 0xc8, 0xad, 0x9c, 0x84, 0x78, 0xd2, 0x6e, 0xe7, 0xef, 0x05, 0x28,
	0x3c, 0xbe, 0x3d, 0x67, 0x7d, 0x23, 0xb6, 0x6e, 0xc4, 0x1e, 0x74, 0x15, 0x75, 0xc4, 0xe3, 0xcb,
	0x47, 0x4d, 0xd1, 0xaa, 0xa6, 0xe8, 0xbb, 0xa6, 0xe8, 0xbd, 0xa1, 0xde, 0xaa, 0xa1, 0xde, 0x57,
	0x43, 0xbd, 0xd7, 0xfb, 0x34, 0x87, 0xac, 0x8c, 0x59, 0x62, 0x16, 0x7c, 0xec, 0xec, 0xd7, 0xe8,
	0x4d, 0x2b, 0x77, 0x39, 0xe8, 0xe5, 0x50, 0x15, 0xca, 0xc5, 0xfb, 0xdd, 0x1f, 0x77, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x3a, 0xd5, 0x73, 0xd6, 0x82, 0x01, 0x00, 0x00,
}

func (m *ClassMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClassMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClassMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		{
			size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCryptonft(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.UpdateRestricted {
		i--
		if m.UpdateRestricted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.BurnRestricted {
		i--
		if m.BurnRestricted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MintRestricted {
		i--
		if m.MintRestricted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCryptonft(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCryptonft(dAtA []byte, offset int, v uint64) int {
	offset -= sovCryptonft(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClassMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCryptonft(uint64(l))
	}
	if m.MintRestricted {
		n += 2
	}
	if m.BurnRestricted {
		n += 2
	}
	if m.UpdateRestricted {
		n += 2
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovCryptonft(uint64(l))
	}
	return n
}

func sovCryptonft(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCryptonft(x uint64) (n int) {
	return sovCryptonft(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClassMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCryptonft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClassMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClassMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCryptonft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCryptonft
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCryptonft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRestricted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCryptonft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MintRestricted = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnRestricted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCryptonft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BurnRestricted = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateRestricted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCryptonft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UpdateRestricted = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCryptonft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCryptonft
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCryptonft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &types.Any{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCryptonft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCryptonft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCryptonft(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCryptonft
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCryptonft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCryptonft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCryptonft
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCryptonft
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCryptonft
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCryptonft        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCryptonft          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCryptonft = fmt.Errorf("proto: unexpected end of group")
)
